name: "resnet50_tensorrt"
platform: "tensorrt_plan"
max_batch_size : 32
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1000]
    label_filename: "labels.txt"
  }
]
model_warmup [
  {
    batch_size: 32
    name: "warmup_requests"
    inputs {
      key: "input"
      value: {
        random_data: true
        dims: [ 3, 224, 224 ]
        data_type: TYPE_FP32
      }
    }
  }
]