name: "nonbatching_minimal"
backend: "minimal"
max_batch_size : 0
input [
  {
    name: "IN0"
    data_type: TYPE_INT32
    dims: [ 4 ]
  }
]
output [
  {
    name: "OUT0"
    data_type: TYPE_INT32
    dims: [ 4]
  }
]
version_policy: { all: {}}
instance_group [
    {
        count: 4
        kind: KIND_CPU
    }
]