name: "minimal_priority_ratelimiter_python"
backend: "python"
input [
  {
    name: "INPUT0"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
instance_group [
    {
        count: 1
        kind: KIND_GPU
        gpus: [0]
        rate_limiter{
          resources[
          {
            name: "R1"
            count: 4
          }
          ]
          priority: 1
        }
    }
]